version: 2.1

orbs:
  android: circleci/android@0.2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.06  # Gunakan image terbaru dengan Java 17
    resource_class: large
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Pastikan pakai Java 17

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Set Java 17
          command: |
            sudo apt update && sudo apt install openjdk-17-jdk -y
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            source $BASH_ENV

      - restore_cache:
          key: android-orb-v1-{{ checksum "build.gradle.kts" }}  # Menggunakan checksum untuk cache yang lebih stabil

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: android-orb-v1-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
